repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.5.0'
    hooks:
    # Run the linter.
    -   id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
    # Run the formatter.
    -   id: ruff-format
        types_or: [ python, pyi, jupyter ]
-   repo: https://github.com/python-poetry/poetry
    rev: '1.5.1'
    hooks:
    -   id: poetry-check
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
    -   id: check-toml
    -   id: check-yaml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: requirements-txt-fixer
