version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.13"
  jobs:
    # https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --only main,docs --all-extras

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - epub
